server:
  port: 5030
spring:
  application:
    name: attendance
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:3030/

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"